// This file was generated by preset-anchor. Programs are exported from this file.

import { Program, AnchorProvider } from "@coral-xyz/anchor";
import { PublicKey } from "@solana/web3.js";
import { IDL, Basic } from "./types"; // This will be generated by anchor build

export const BASIC_PROGRAM_ID = new PublicKey(IDL.address);

export async function getBasicProgram(provider: AnchorProvider) {
  return await Program.at<Basic>(
    BASIC_PROGRAM_ID,
    provider
  );
}

export { IDL };
