[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
basic = "BTZP9trae9yh7Pugqy3Dy688B63SjqUpXMo4MLtbQqiA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 20000
shutdown_wait = 2000
upgradeable = false

[test.validator]
url = "http://127.0.0.1:8899"
bind_address = "127.0.0.1"
ledger = "test-ledger"
rpc_port = 8899
commitment = "processed"
reset = true
